[metadata]
name = mmVelo-tutorials
version = 0.1.0
author = Satoshi Nomura
author_email = nomura.satoshi.z4@s.mail.nagoya-u.ac.jp
description = Tutorials for mmVelo: a deep generative model for estimating cell state-dependent dynamics across multiple modalities
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/nomuhyooon/mmVelo
project_urls =
    Bug Tracker = https://github.com/nomuhyooon/mmVelo/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
python_requires = >=3.8
install_requires =
    numpy
    pandas
    scipy
    matplotlib
    seaborn
    anndata>=0.8.0
    scanpy>=1.9.0
    scvelo>=0.2.4
    torch>=2.0.0
    pytorch-lightning>=1.6.0
    leidenalg
    umap-learn
    statsmodels
    jupyter
